version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: flutter_secure_storage
        update-types: ["version-update:semver-major"]
