name: dakit_workspace
description: Workspace for the DAKit DeviantArt client SDK.
publish_to: none
version: 0.1.0-dev.1

environment:
  sdk: ^3.13.1

workspace:
  - packages/dakit_core
  - packages/dakit_api
  - packages/dakit_flutter
  - apps/example_client

dev_dependencies:
  lints: ^6.0.0
