name: dakit_cli
description: Command-line client for DAKit.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.13.1

resolution: workspace

executables:
  dakit: dakit
  devart-dl: devart_dl

dependencies:
  args: ^2.7.0
  crypto: ^3.0.7
  dakit_api: ^0.1.0
  dakit_core: ^0.1.0
  dio: ^5.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
