name: dakit_flutter
description: Flutter platform integrations for the DAKit DeviantArt client SDK.
version: 0.1.8
repository: https://github.com/redtidev1918/dakit/tree/main/packages/dakit_flutter
resolution: workspace

environment:
  sdk: ^3.13.1
  flutter: ">=3.47.1"

dependencies:
  app_links: ^7.2.1
  dakit_api: ^0.1.0
  dakit_core: ^0.1.0
  background_downloader: ^9.5.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
