name: Publish dakit_web

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1
    with:
      working-directory: packages/dakit_web
